// design-tokens/build.mjs
// tokens.json (Figma export) -> styles/tokens.css + styles/typography.css
// Run: npm run tokens:build. Never edit the generated CSS by hand.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const data = JSON.parse(readFileSync(join(root, "design-tokens/tokens.json"), "utf8"));

// Collections named "N. Something" are canonical. Anything else is emitted
// under a --legacy-* namespace so it can never collide with or override the
// canonical system, and the build warns so someone notices.
const isCanonical = (name) => /^\d+\.\s/.test(name);
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const warnings = [];

// 1. assign a CSS name to every token
const cssName = new Map();          // token name -> css custom property
const entries = [];                 // { coll, name, token }
for (const [coll, def] of Object.entries(data.collections)) {
  const prefix = isCanonical(coll) ? "" : `legacy-${slug(coll)}-`;
  if (!isCanonical(coll)) warnings.push(`Unnumbered collection "${coll}" emitted as --${prefix}*`);
  for (const [name, token] of Object.entries(def.tokens)) {
    const prop = `--${prefix}${slug(name)}`;
    if (isCanonical(coll)) {
      if (cssName.has(name)) throw new Error(`Duplicate token name across collections: ${name}`);
      cssName.set(name, prop);
    }
    entries.push({ coll, name, token, prop, modes: def.modes });
  }
}

// 2. format a single value
const format = (name, token, value) => {
  if (value && typeof value === "object" && "alias" in value) {
    const target = cssName.get(value.alias);
    if (!target) throw new Error(`Unresolved alias ${name} -> ${value.alias}`);
    return `var(${target})`;
  }
  if (token.type === "COLOR") return value;
  if (token.type === "FLOAT") {
    if (name.startsWith("line-height/")) return String(value / 100);
    return `${value}px`;
  }
  return JSON.stringify(value);
};

// 3. group by mode. First mode of every collection goes on :root.
const blocks = new Map([[":root", []]]);
for (const e of entries) {
  e.modes.forEach((mode, i) => {
    const value = e.token.values[mode];
    if (value === undefined) return;
    const selector = i === 0 ? ":root" : `[data-theme="${slug(mode.split(" ")[0])}"]`;
    if (!blocks.has(selector)) blocks.set(selector, []);
    blocks.get(selector).push(`  ${e.prop}: ${format(e.name, e.token, value)};`);
  });
}

// 4. effects -> box-shadow strings
const shadow = (fx) => fx.map(({ x, y, blur, spread, color: c }) =>
  `${x}px ${y}px ${blur}px ${spread}px rgba(${Math.round(c.r * 255)}, ${Math.round(c.g * 255)}, ${Math.round(c.b * 255)}, ${+c.a.toFixed(3)})`
).join(", ");
for (const s of data.effects) blocks.get(":root").push(`  --effect-${slug(s.name)}: ${shadow(s.effects)};`);

const header = "/* GENERATED by design-tokens/build.mjs from tokens.json. Do not edit. */\n";
let css = header;
for (const [sel, lines] of blocks) {
  const s = sel === ":root" ? ':root,\n[data-theme="app"]' : sel;
  css += `\n${s} {\n${lines.join("\n")}\n}\n`;
}

// 5. text styles -> Tailwind v4 utilities, e.g. `type-heading-h1`
const weight = { Regular: 400, Medium: 500, "Semi Bold": 600, SemiBold: 600, Bold: 700, "Extra Bold": 800, ExtraBold: 800 };
const family = (f) => ({
  Inter: 'var(--font-sans)',
  "Instrument Serif": 'var(--font-serif)',
  "Plus Jakarta Sans": 'var(--font-label)',
}[f] ?? `"${f}", var(--font-sans)`);
// A family counts as loaded when app/layout.tsx imports its @fontsource package.
const layout = readFileSync(join(root, "app/layout.tsx"), "utf8");
const loaded = (f) => f === "Inter" || new RegExp(`@fontsource(-variable)?/${slug(f)}\\b`).test(layout);
let type = header;
for (const t of data.text) {
  const lh = t.lineHeightUnit === "PERCENT" ? String(+(t.lineHeight / 100).toFixed(3)) : `${t.lineHeight}px`;
  type += `\n@utility type-${slug(t.name)} {\n  font-family: ${family(t.family)};\n  font-size: ${t.size}px;\n  font-weight: ${weight[t.style] ?? 400};\n  line-height: ${lh};\n  letter-spacing: ${t.letterSpacing}px;\n}\n`;
  if (!loaded(t.family)) warnings.push(`Text style "${t.name}" uses ${t.family}. Load it in app/layout.tsx or this style falls back to the system font.`);
}

mkdirSync(join(root, "styles"), { recursive: true });
writeFileSync(join(root, "styles/tokens.css"), css);
writeFileSync(join(root, "styles/typography.css"), type);
const count = entries.length + data.effects.length;
console.log(`tokens: ${count} variables and effects, ${data.text.length} text styles`);
[...new Set(warnings)].forEach((w) => console.warn(`  warn: ${w}`));
